#!/usr/bin/env python3
"""Generate website/data.html from the study output.

The data page is the one place on the site where every number appears at once, so it is
generated rather than written: re-run the study, re-run this, and the page reports what
the study actually found. Nothing on it is typed by hand.

    python website/make_data_page.py
"""

from __future__ import annotations

import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = json.loads((ROOT / "part_a" / "results.json").read_text(encoding="utf-8"))
ANALYSIS = json.loads((ROOT / "part_a" / "analysis.json").read_text(encoding="utf-8"))
OUT = ROOT / "website" / "data.html"

NAV = """<nav class="nav">
  <div class="nav-inner">
    <a class="brand" href="/"><span class="dot"></span>AgentCage</a>
    <a class="link" href="/">Overview</a>
    <a class="link" href="/manifesto">Manifesto</a>
    <a class="link" href="/paper">Paper</a>
    <a class="link" href="/models">Models</a>
    <a class="link" href="/data" aria-current="page">Data</a>
    <a class="link" href="https://github.com/RithikSatarla/agentcage">GitHub</a>
  </div>
</nav>"""


def meter(covered: int, uncovered: int) -> str:
    total = covered + uncovered or 1
    cov_pct = 100.0 * covered / total
    return (
        f'<span class="meter" role="img" aria-label="{covered} covered, {uncovered} uncovered">'
        f'<span class="cov" style="width:{cov_pct:.1f}%"></span>'
        f'<span class="unc" style="width:{100 - cov_pct:.1f}%"></span></span>'
    )


def repo_rows() -> str:
    """Rows carry data-* sort keys. Sorting on rendered text would break on percent
    signs, meters and pills, so the numbers travel separately from their display."""
    rows = []
    for r in sorted(ANALYSIS["repos"], key=lambda x: -x["uncovered"]):
        scan = ("full" if r["exhaustive_scan"] else "capped")
        scan_cls = "live" if r["exhaustive_scan"] else "pending"
        rows.append(
            f'    <tr data-repo="{html.escape(r["repo"].lower())}" data-scan="{scan}" '
            f'data-tools="{r["tools"]}" data-covered="{r["covered"]}" '
            f'data-uncovered="{r["uncovered"]}" data-pct="{r["uncovered_pct"]}">'
            f'<td class="name">{html.escape(r["repo"])}</td>'
            f'<td class="n">{r["tools"]}</td>'
            f'<td class="n">{r["covered"]}</td>'
            f'<td class="n">{r["uncovered"]}</td>'
            f'<td class="n">{r["uncovered_pct"]}%</td>'
            f"<td>{meter(r['covered'], r['uncovered'])}</td>"
            f'<td><span class="pill {scan_cls}">{scan}</span></td></tr>'
        )
    return "\n".join(rows)


def category_rows() -> str:
    rows = []
    for c in sorted(ANALYSIS["categories"], key=lambda x: -x["uncovered_pct"]):
        lo, hi = c["ci95"]
        rows.append(
            f'    <tr data-label="{html.escape(c["label"].lower())}" '
            f'data-tools="{c["tools"]}" data-uncovered="{c["uncovered"]}" '
            f'data-pct="{c["uncovered_pct"]}">'
            f'<td>{html.escape(c["label"])}</td>'
            f'<td class="n">{c["tools"]}</td>'
            f'<td class="n">{c["uncovered"]}</td>'
            f'<td class="n">{c["uncovered_pct"]}%</td>'
            f'<td class="n">{lo}–{hi}%</td>'
            f"<td>{meter(c['covered'], c['uncovered'])}</td></tr>"
        )
    return "\n".join(rows)


def screened_out_list() -> str:
    names = sorted(RESULTS["screened_out_no_write_tools"], key=str.lower)
    return ", ".join(f"<code>{html.escape(n)}</code>" for n in names)


def build() -> str:
    a, d = ANALYSIS, RESULTS
    lo, hi = a["uncovered_ci95"]
    sens = d["sensitivity_exhaustive_test_scan_only"]
    conc = a["concentration"]

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Data — AgentCage</title>
<meta name="description" content="Every repository, category and tool behind the {a['uncovered_pct']}% figure, with confidence intervals and the raw JSON.">
<link rel="stylesheet" href="styles.css">
</head>
<body>

<!-- GENERATED by website/make_data_page.py from part_a/results.json and analysis.json.
     Do not edit by hand: re-run the study, then re-run the generator. -->

{NAV}

<header class="hero">
  <div class="wrap">
    <p class="label">Study run {d['timestamp'][:10]}</p>
    <h1>Every number, and<br>where it came from.</h1>
    <p class="lede">{a['tools_total']} write-capable tool definitions across
    {d['total_repos_analyzed']} repositories, screened from {d['candidates_screened']}
    candidates. Reproduce it with <code>python -m part_a.run</code> — no credentials
    needed.</p>
    <div class="actions">
      <a class="btn solid" href="https://github.com/RithikSatarla/agentcage/blob/main/part_a/results.json">results.json</a>
      <a class="btn" href="https://github.com/RithikSatarla/agentcage/blob/main/part_a/analysis.json">analysis.json</a>
      <a class="btn" href="https://github.com/RithikSatarla/agentcage/blob/main/PROTOCOL.md">Method</a>
    </div>
  </div>
</header>

<section class="flush">
  <div class="wrap">
    <div class="stats">
      <div class="stat"><div class="v hot">{a['uncovered_pct']}%</div>
        <span class="k">never referenced by a test</span></div>
      <div class="stat"><div class="v">{a['tools_uncovered']}/{a['tools_total']}</div>
        <span class="k">uncovered / total tools</span></div>
      <div class="stat"><div class="v">{lo}–{hi}%</div>
        <span class="k">95% Wilson interval</span></div>
      <div class="stat"><div class="v">{sens['write_tools_uncovered_pct']}%</div>
        <span class="k">exhaustive scans only</span></div>
    </div>
    <p class="caption">The sensitivity figure covers the {sens['repos_analyzed']}
    repositories whose entire test suite was read, where a missed reference cannot be a
    sampling artefact. Its agreement with the headline is the reason to trust it.</p>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="head">
      <h2>By repository</h2>
      <p class="lede">A tool counts as covered if its identifier appears anywhere in
      that repository's test sources — no assertion, no execution required.</p>
    </div>
    <div class="filters">
      <input type="search" id="repo-search" placeholder="filter repositories…"
             aria-label="Filter repositories by name">
      <button class="chip" type="button" data-scan="all" aria-pressed="true">all scans</button>
      <button class="chip" type="button" data-scan="full" aria-pressed="false">exhaustive only</button>
      <button class="chip" type="button" data-untested="1" aria-pressed="false">has untested tools</button>
      <span class="rowcount" id="repo-count"></span>
    </div>
    <div class="scroll">
      <table class="data" id="repo-table">
        <thead>
          <tr><th class="sortable" data-key="repo">Repository</th>
              <th class="n sortable" data-key="tools">Tools</th>
              <th class="n sortable" data-key="covered">Covered</th>
              <th class="n sortable" data-key="uncovered" aria-sort="descending">Uncov.</th>
              <th class="n sortable" data-key="pct">Share</th>
              <th>Split</th><th>Test scan</th></tr>
        </thead>
        <tbody>
{repo_rows()}
        </tbody>
        <tfoot>
          <tr><td>Total</td><td class="n">{a['tools_total']}</td>
              <td class="n">{a['tools_total'] - a['tools_uncovered']}</td>
              <td class="n">{a['tools_uncovered']}</td>
              <td class="n">{a['uncovered_pct']}%</td><td></td><td></td></tr>
        </tfoot>
      </table>
    </div>
    <p class="caption"><strong>{conc['share_of_all_uncovered']}% of all untested tools sit
    in three repositories</strong>, each shipping a large tool catalogue. Pooling across
    repositories of very different sizes describes the ecosystem's tool population rather
    than a typical project. <em>Capped</em> means the per-repository read limit bound, so
    that repository's coverage is an upper bound.</p>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="head">
      <h2>By kind of write operation</h2>
      <p class="lede">Each tool carries the categories that qualified it. Categories
      overlap — a tool may match several — so the counts do not sum to
      {a['tools_total']}.</p>
    </div>
    <div class="scroll">
      <table class="data" id="cat-table">
        <thead>
          <tr><th class="sortable" data-key="label">Kind of write operation</th>
              <th class="n sortable" data-key="tools">Tools</th>
              <th class="n sortable" data-key="uncovered">Uncov.</th>
              <th class="n sortable" data-key="pct" aria-sort="descending">Share</th>
              <th class="n">95% CI</th><th>Split</th></tr>
        </thead>
        <tbody>
{category_rows()}
        </tbody>
      </table>
    </div>
    <div class="note" style="margin-top:1.4rem"><strong>Read the intervals, not the
    ordering.</strong> Several categories hold fewer than 20 tools and their intervals
    overlap heavily. The claim is only that the extremes separate: version-control and
    shell tools are less covered than database and filesystem tools.</div>

    <figure class="chart" style="margin-top:1.6rem">
      <img class="fig-light" src="figures/fig_category_light.svg"
           alt="Test coverage by kind of write operation, as a stacked bar chart.">
      <img class="fig-dark" src="figures/fig_category_dark.svg" alt="" aria-hidden="true">
    </figure>
    <figure class="chart" style="margin-top:1.2rem">
      <img class="fig-light" src="figures/fig_repos_light.svg"
           alt="Write-capable tool definitions per repository, split by coverage.">
      <img class="fig-dark" src="figures/fig_repos_dark.svg" alt="" aria-hidden="true">
    </figure>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="head">
      <h2>What screened out, and why it matters</h2>
    </div>
    <p>A repository enters the analysed set only if the detectors find at least one
    write-capable tool definition. Screening is mechanical:
    <strong>{len(d['screened_out_no_write_tools'])} of {d['candidates_screened']}
    candidates were excluded by the code</strong>, not by hand.</p>
    <div class="note"><strong>This is the study's dominant limitation.</strong> Screening
    out is not a claim that a project performs no writes — it means the project exposes no
    framework-idiomatic tool definition whose body performs a detectable write. Agents with
    bespoke architectures write to disk and shell out constantly but expose no
    <code>@tool</code> or <code>BaseTool</code> surface. The denominator of
    {d['total_repos_analyzed']} reflects detector coverage as much as the ecosystem.</div>
    <p class="caption" style="margin-top:1.2rem">Screened out: {screened_out_list()}</p>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="head"><h2>Reproduce it</h2></div>
<pre><code>git clone https://github.com/RithikSatarla/agentcage.git
cd agentcage &amp;&amp; pip install -e ".[dev]"

python -m part_a.run          # the study, {d['candidates_screened']} repos at HEAD
python -m part_a.analyze      # intervals, categories, figures
pytest tests/                 # full suite, no network</code></pre>
    <p>The study costs {d['candidates_screened']} GitHub API calls, inside the
    unauthenticated hourly limit. Responses cache under <code>.cache/</code>, so a second
    run is nearly instant. It re-runs weekly in CI, and every push re-runs the pipeline
    against the live API.</p>
    <p class="caption">Files are read at <code>HEAD</code>, so re-running later measures
    later code. This page was generated from the run of {d['timestamp'][:10]}.</p>
  </div>
</section>

<footer>
  <div class="wrap">
    <p>MIT licensed ·
    <a href="https://github.com/RithikSatarla/agentcage">github.com/RithikSatarla/agentcage</a><br>
    Generated by <code>tools/make_data_page.py</code>. Part A is exploratory; Part B is
    pre-registered and has not been run.</p>
  </div>
</footer>

<script>
(function () {{
  "use strict";

  // Sorting reads data-* attributes rather than cell text: the rendered cells carry
  // percent signs, meters and pills, none of which sort correctly as strings.
  function sortable(tableId, numericKeys) {{
    var table = document.getElementById(tableId);
    if (!table) {{ return; }}
    var body = table.tBodies[0];

    Array.prototype.forEach.call(table.querySelectorAll("th.sortable"), function (th) {{
      th.setAttribute("tabindex", "0");
      th.setAttribute("role", "button");

      function activate() {{
        var key = th.getAttribute("data-key");
        var desc = th.getAttribute("aria-sort") !== "descending";
        Array.prototype.forEach.call(table.querySelectorAll("th.sortable"), function (o) {{
          o.removeAttribute("aria-sort");
        }});
        th.setAttribute("aria-sort", desc ? "descending" : "ascending");

        var rows = Array.prototype.slice.call(body.rows);
        rows.sort(function (a, b) {{
          var av = a.getAttribute("data-" + key), bv = b.getAttribute("data-" + key);
          var cmp = numericKeys.indexOf(key) >= 0
            ? parseFloat(av) - parseFloat(bv)
            : String(av).localeCompare(String(bv));
          return desc ? -cmp : cmp;
        }});
        rows.forEach(function (r) {{ body.appendChild(r); }});
      }}

      th.addEventListener("click", activate);
      th.addEventListener("keydown", function (e) {{
        if (e.key === "Enter" || e.key === " ") {{ e.preventDefault(); activate(); }}
      }});
    }});
  }}

  sortable("repo-table", ["tools", "covered", "uncovered", "pct"]);
  sortable("cat-table", ["tools", "uncovered", "pct"]);

  // Repository filters: free-text search plus two mutually independent toggles.
  var search = document.getElementById("repo-search");
  var chips = document.querySelectorAll(".filters .chip");
  var repoBody = document.getElementById("repo-table").tBodies[0];
  var count = document.getElementById("repo-count");
  var scanFilter = "all", untestedOnly = false;

  function applyFilters() {{
    var q = (search.value || "").trim().toLowerCase();
    var shown = 0, total = repoBody.rows.length;
    Array.prototype.forEach.call(repoBody.rows, function (row) {{
      var okName = !q || row.getAttribute("data-repo").indexOf(q) >= 0;
      var okScan = scanFilter === "all" || row.getAttribute("data-scan") === scanFilter;
      var okUnt = !untestedOnly || parseInt(row.getAttribute("data-uncovered"), 10) > 0;
      var visible = okName && okScan && okUnt;
      row.style.display = visible ? "" : "none";
      if (visible) {{ shown += 1; }}
    }});
    count.textContent = shown === total
      ? total + " repositories"
      : shown + " of " + total + " repositories";
  }}

  Array.prototype.forEach.call(chips, function (chip) {{
    chip.addEventListener("click", function () {{
      if (chip.hasAttribute("data-scan")) {{
        scanFilter = chip.getAttribute("data-scan");
        Array.prototype.forEach.call(chips, function (c) {{
          if (c.hasAttribute("data-scan")) {{
            c.setAttribute("aria-pressed", String(c === chip));
          }}
        }});
      }} else {{
        untestedOnly = chip.getAttribute("aria-pressed") !== "true";
        chip.setAttribute("aria-pressed", String(untestedOnly));
      }}
      applyFilters();
    }});
  }});

  search.addEventListener("input", applyFilters);
  applyFilters();
}})();
</script>

</body>
</html>
"""


def main() -> int:
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {len(ANALYSIS['repos'])} repo rows, {len(ANALYSIS['categories'])} category rows")
    print(f"  headline {ANALYSIS['uncovered_pct']}% of {ANALYSIS['tools_total']} tools")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
