#!/usr/bin/env python3
"""Generate the paper's numbers from part_a/results.json.

Every statistic in the paper comes from here. Nothing is typed into the LaTeX by
hand, so the paper cannot drift from the data: re-run the study, re-run this, and
the paper reports whatever the study actually found.

    python paper/make_tables.py

Writes paper/generated_macros.tex and paper/generated_table.tex.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "part_a" / "results.json"
OUT_DIR = Path(__file__).resolve().parent


def tex_escape(text: str) -> str:
    for bad, good in (("_", r"\_"), ("&", r"\&"), ("%", r"\%"), ("#", r"\#")):
        text = text.replace(bad, good)
    return text


def main() -> int:
    d = json.loads(RESULTS.read_text(encoding="utf-8"))
    sens = d["sensitivity_exhaustive_test_scan_only"]
    analyzed = [r for r in d["repos"] if r.get("has_write_ops")]
    analyzed.sort(key=lambda r: -int(r["write_tool_count"]))

    macros = {
        "AcCandidates": d["candidates_screened"],
        "AcScreenedOut": len(d["screened_out_no_write_tools"]),
        "AcRepos": d["total_repos_analyzed"],
        "AcTools": d["write_tools_total"],
        "AcCovered": d["write_tools_covered"],
        "AcUncovered": d["write_tools_uncovered"],
        "AcUncoveredPct": f"{d['write_tools_uncovered_pct']}\\%",
        "AcRepoUntested": d["untested"],
        "AcRepoUntestedPct": f"{d['untested_pct']}\\%",
        "AcSensRepos": sens["repos_analyzed"],
        "AcSensTools": sens["write_tools_total"],
        "AcSensUncovered": sens["write_tools_uncovered"],
        "AcSensPct": f"{sens['write_tools_uncovered_pct']}\\%",
        "AcRunDate": d["timestamp"][:10],
        "AcUntestedRepoList": ", ".join(tex_escape(r) for r in d["untested_repos"]),
    }

    lines = ["% GENERATED by paper/make_tables.py -- do not edit by hand.", ""]
    for name, value in macros.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    (OUT_DIR / "generated_macros.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # The COMPLETE table environment is generated, and the paper inputs it at top
    # level. Inputting a bare row fragment inside a tabular instead makes TeX
    # misplace the \noalign of the following \bottomrule and the build fails.
    rows = [
        "% GENERATED by paper/make_tables.py -- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lrrrrl}",
        "\\toprule",
        "Repository & Tools & Covered & Uncovered & Uncov. & Test scan \\\\",
        "\\midrule",
    ]
    for r in analyzed:
        total = int(r["write_tool_count"])
        covered = int(r["covered_write_tools"])
        pct = 100.0 * (total - covered) / total if total else 0.0
        scan = "full" if r.get("coverage_scan_complete") else "capped"
        rows.append(
            f"{tex_escape(r['repo'])} & {total} & {covered} & {total - covered} & "
            f"{pct:.0f}\\% & {scan} \\\\"
        )
    rows.append("\\midrule")
    rows.append(
        f"\\textbf{{Total}} & \\textbf{{{d['write_tools_total']}}} & "
        f"\\textbf{{{d['write_tools_covered']}}} & \\textbf{{{d['write_tools_uncovered']}}} & "
        f"\\textbf{{{d['write_tools_uncovered_pct']}\\%}} & \\\\"
    )
    rows += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Write-capable tool definitions and their test coverage, for the run of "
        f"{d['timestamp'][:10]}. ``Test scan'' is \\emph{{full}} where the repository's entire "
        "test suite was read and \\emph{capped} where the per-repository read limit bound. "
        "Generated directly from \\texttt{part\\_a/results.json}.}",
        "\\label{tab:parta}",
        "\\end{table}",
    ]
    (OUT_DIR / "generated_table.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")

    print(f"wrote generated_macros.tex ({len(macros)} macros)")
    print(f"wrote generated_table.tex ({len(analyzed)} rows)")
    print(f"headline: {d['write_tools_uncovered_pct']}% of {d['write_tools_total']} tools")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
