#!/usr/bin/env python3
"""Generate the paper's numbers from part_a/results.json.

Every statistic in the paper comes from here. Nothing is typed into the LaTeX by
hand, so the paper cannot drift from the data: re-run the study, re-run this, and
the paper reports whatever the study actually found.

    python paper/make_tables.py

Writes paper/generated_macros.tex and paper/generated_table.tex.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "part_a" / "results.json"
ANALYSIS = ROOT / "part_a" / "analysis.json"
OUT_DIR = Path(__file__).resolve().parent


def tex_escape(text: str) -> str:
    for bad, good in (("_", r"\_"), ("&", r"\&"), ("%", r"\%"), ("#", r"\#")):
        text = text.replace(bad, good)
    return text


PARTB = ROOT / "part_b" / "partb_results.json"

#: The three agents, keyed as they appear in the results, with the one-line description
#: of what each one got wrong. The mechanism differs per agent and the paper says so;
#: writing "duplicate write" three times would hide that two of them share a root cause.
DEFECT_PROSE = {
    "camel-ai/camel": (
        "reads a file from the default branch with no \\texttt{ref}, then writes that "
        "blob sha to a different branch; the resulting 409 is uncaught"),
    "agno-agi/agno": (
        "one \\texttt{create\\_issue} call creates two issues after the transport "
        "retries beneath the tool; one success is reported"),
    "run-llama/llama_index": (
        "the same shape in an independently written client; both drive "
        "\\texttt{python-jira}, so the two observations share a root cause"),
}


def breakable(text: str) -> str:
    """Escape for TeX and let long identifiers wrap inside a narrow column.

    A ``p{}`` column breaks at spaces, and ``run-llama/llama_index`` has none, so it
    overflows into whatever is to its right. Permitting a break after the separators
    keeps the cell inside its column.
    """
    return (tex_escape(text)
            .replace("/", "/\\allowbreak{}")
            .replace("\\_", "\\_\\allowbreak{}"))


def part_b_macros() -> dict:
    """Part B's headline numbers, so the paper cannot drift from the run either."""
    if not PARTB.exists():
        return {}
    b = json.loads(PARTB.read_text(encoding="utf-8"))
    primary = b["primary_outcome"]
    secondary = b["secondary_outcomes"]
    tiers = secondary["tiers"]
    graded = secondary["requests_graded"]

    def pct(n: int) -> str:
        return f"{100.0 * n / graded:.0f}\\%" if graded else "n/a"

    return {
        "BbAgentsRun": primary["denominator"],
        "BbAgentsDefective": primary["numerator"],
        "BbThresholdPct": f"{int(primary['falsification_threshold'] * 100)}\\%",
        "BbExcluded": len(b["exclusions"]),
        "BbFrameAgents": b["agents_in_frame"],
        "BbRequests": graded,
        "BbTOne": tiers["T1"],
        "BbTTwo": tiers["T2"],
        "BbTThree": tiers["T3"],
        "BbMiss": tiers["MISS"],
        "BbTOnePct": pct(tiers["T1"]),
        "BbTTwoPct": pct(tiers["T2"]),
        "BbDuplicateWrites": secondary["defects_by_class"]["1"],
        "BbStaleReads": secondary["defects_by_class"]["3"],
        "BbUncheckedErrors": secondary["defects_by_class"]["2"],
        "BbKillEvaluable": "no" if not secondary["kill_criterion_evaluable"] else "yes",
    }


def part_b_table() -> str:
    """One row per agent run: what it is, whether its suite passes, what broke."""
    b = json.loads(PARTB.read_text(encoding="utf-8"))
    rows = [
        "% GENERATED by paper/make_tables.py -- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\begin{tabular}{p{3.0cm}p{2.5cm}cp{5.0cm}}",
        "\\toprule",
        "Agent & Tool & Suite & Defect observed against the model \\\\",
        "\\midrule",
    ]
    for agent in b["agents"]:
        classes = ", ".join(f"class~{d['class']} ({d['name']})" for d in agent["defects"])
        rows.append(
            f"\\texttt{{{breakable(agent['agent'])}}} & "
            f"\\texttt{{{breakable(agent['tool'])}}} & "
            f"pass & {classes}: {DEFECT_PROSE.get(agent['agent'], '')} \\\\"
        )
    rows += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{The three agents run in Part B. Every suite passes; every agent "
        "exhibits a pre-registered defect class when the same write paths are driven "
        "against a stateful model. Generated from "
        "\\texttt{part\\_b/partb\\_results.json}.}",
        "\\label{tab:partb}",
        "\\end{table}",
    ]
    return "\n".join(rows) + "\n"


def main() -> int:
    d = json.loads(RESULTS.read_text(encoding="utf-8"))
    a = json.loads(ANALYSIS.read_text(encoding="utf-8"))
    sens = d["sensitivity_exhaustive_test_scan_only"]
    by_cat = {c["category"]: c for c in a["categories"]}
    analyzed = [r for r in d["repos"] if r.get("has_write_ops")]
    analyzed.sort(key=lambda r: -int(r["write_tool_count"]))

    macros = {
        "AcCandidates": d["candidates_screened"],
        "AcScreenedOut": len(d["screened_out_no_write_tools"]),
        "AcRepos": d["total_repos_analyzed"],
        "AcTools": d["write_tools_total"],
        "AcCovered": d["write_tools_covered"],
        "AcUncovered": d["write_tools_uncovered"],
        "AcUncoveredPct": f"{d['write_tools_uncovered_pct']}\\%",
        "AcRepoUntested": d["untested"],
        "AcRepoUntestedPct": f"{d['untested_pct']}\\%",
        "AcSensRepos": sens["repos_analyzed"],
        "AcSensTools": sens["write_tools_total"],
        "AcSensUncovered": sens["write_tools_uncovered"],
        "AcSensPct": f"{sens['write_tools_uncovered_pct']}\\%",
        "AcRunDate": d["timestamp"][:10],
        "AcUntestedRepoList": ", ".join(tex_escape(r) for r in d["untested_repos"]),
        # secondary analysis
        "AcCiLo": a["uncovered_ci95"][0],
        "AcCiHi": a["uncovered_ci95"][1],
        "AcConcPct": f"{a['concentration']['share_of_all_uncovered']}\\%",
        "AcVcsPct": f"{by_cat['vcs_write']['uncovered_pct']}\\%",
        "AcShellPct": f"{by_cat['shell_exec']['uncovered_pct']}\\%",
        "AcShellN": by_cat["shell_exec"]["tools"],
        "AcShellUncovered": by_cat["shell_exec"]["uncovered"],
        "AcVcsN": by_cat["vcs_write"]["tools"],
        "AcVcsUncovered": by_cat["vcs_write"]["uncovered"],
        "AcPaymentN": by_cat.get("payment_write", {}).get("tools", 0),
    }
    macros.update(part_b_macros())

    lines = ["% GENERATED by paper/make_tables.py -- do not edit by hand.", ""]
    for name, value in macros.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    (OUT_DIR / "generated_macros.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # The COMPLETE table environment is generated, and the paper inputs it at top
    # level. Inputting a bare row fragment inside a tabular instead makes TeX
    # misplace the \noalign of the following \bottomrule and the build fails.
    rows = [
        "% GENERATED by paper/make_tables.py -- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lrrrrl}",
        "\\toprule",
        "Repository & Tools & Covered & Uncovered & Uncov. & Test scan \\\\",
        "\\midrule",
    ]
    for r in analyzed:
        total = int(r["write_tool_count"])
        covered = int(r["covered_write_tools"])
        pct = 100.0 * (total - covered) / total if total else 0.0
        scan = "full" if r.get("coverage_scan_complete") else "capped"
        rows.append(
            f"{tex_escape(r['repo'])} & {total} & {covered} & {total - covered} & "
            f"{pct:.0f}\\% & {scan} \\\\"
        )
    rows.append("\\midrule")
    rows.append(
        f"\\textbf{{Total}} & \\textbf{{{d['write_tools_total']}}} & "
        f"\\textbf{{{d['write_tools_covered']}}} & \\textbf{{{d['write_tools_uncovered']}}} & "
        f"\\textbf{{{d['write_tools_uncovered_pct']}\\%}} & \\\\"
    )
    rows += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Write-capable tool definitions and their test coverage, for the run of "
        f"{d['timestamp'][:10]}. ``Test scan'' is \\emph{{full}} where the repository's entire "
        "test suite was read and \\emph{capped} where the per-repository read limit bound. "
        "Generated directly from \\texttt{part\\_a/results.json}.}",
        "\\label{tab:parta}",
        "\\end{table}",
    ]
    (OUT_DIR / "generated_table.tex").write_text("\n".join(rows) + "\n", encoding="utf-8")

    # Category table, complete environment (see note above on \input inside tabular).
    cat_rows = [
        "% GENERATED by paper/make_tables.py -- do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\begin{tabular}{lrrrl}",
        "\\toprule",
        "Kind of write operation & Tools & Uncov. & Share & 95\\% CI \\\\",
        "\\midrule",
    ]
    for c in sorted(a["categories"], key=lambda c: -c["uncovered_pct"]):
        lo, hi = c["ci95"]
        cat_rows.append(
            f"{tex_escape(c['label'])} & {c['tools']} & {c['uncovered']} & "
            f"{c['uncovered_pct']}\\% & {lo}--{hi}\\% \\\\"
        )
    cat_rows += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{Coverage by kind of write operation. Categories overlap---a tool may "
        "match several---so the counts do not sum to the total. Intervals are Wilson 95\\% "
        "score intervals. Generated from \\texttt{part\\_a/analysis.json}.}",
        "\\label{tab:category}",
        "\\end{table}",
    ]
    (OUT_DIR / "generated_category_table.tex").write_text(
        "\n".join(cat_rows) + "\n", encoding="utf-8"
    )

    if PARTB.exists():
        (OUT_DIR / "generated_partb_table.tex").write_text(part_b_table(),
                                                           encoding="utf-8")
        b = json.loads(PARTB.read_text(encoding="utf-8"))
        print(f"wrote generated_partb_table.tex ({len(b['agents'])} rows)")

    print(f"wrote generated_macros.tex ({len(macros)} macros)")
    print(f"wrote generated_category_table.tex ({len(a['categories'])} rows)")
    print(f"wrote generated_table.tex ({len(analyzed)} rows)")
    print(f"headline: {d['write_tools_uncovered_pct']}% of {d['write_tools_total']} tools")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
